# Generated by Django 4.0 on 2021-12-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoshistore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
